apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: wltjd9870/kafka-cli:v0.0.6
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
        command:
        - kafka-client
        - -mode=producer
        - -brokers=127.0.0.1:9092
        - -data-type=image
        - -topic=kafka-test-image
